### ISSUE TITLE
Ranked Pings at only certain times

### ISSUE THREAD

**Issue by AC1937** [CTN-Originals/HeatseekerHeaven-DiscordBot#15]
Allow the ability for a person to only be pinged at certain times. One idea I had for implementation was to have roles for 3 8 hour periods that can be opted in and out of and just pinging those roles during the set times.

**Comment by 8CTN8** [comment]
After thinking about this for a while, this might prove to be very difficult to implement. And for this to work properly, we would also need a larger player base. Im closing this for now but might re-open when the possibilities are a bit more in favor.
