### ISSUE TITLE
Better rank system

### ISSUE THREAD

**Issue by TiTaNiuMx1** [CTN-Originals/HeatseekerHeaven-DiscordBot#25]
When someone joins and starts playing rank he will need to play 5 or 10 games for he's placement 

after the placement he will get he's rank on how well he did in he's placements 
For the ranks, each rank has a range and from my experience playing and grinding heatseeker rank i believe these are the best ranges for all ranks 
Prospect (below 950) or (below 1000)
Challenger (950-1049) or (1000-1099)
Rising star (1050-1199) or (1100-1249)
Champion (1200+) or (1250+)

Note : the range will be focused on the global MMR

**Comment by 8CTN8** [comment]
This issue will stay marked as suggestion until enough people agree with this, when that happens it will be given a prio level

**Comment by Brambleburri** [comment]
I like this

**Comment by 8CTN8** [comment]
This issue has been discussed with most admins and our final decision is against this idea as this would only work correctly with a larger player base
